version: '3.9'

services:
  
  render-app-frontend:
    container_name: render-app-frontend
    build: ../render-app-frontend
    command:
      - /bin/sh
      - -c
      - |
        /app/node_modules/.bin/gatsby develop -H 0.0.0.0
    ports: 
      - 8000:8000
    environment:
      HOST: '0.0.0.0'
      PORT: 8000
    volumes:
      - ./../render-app-frontend/public:/app/public
    networks:
      - general

  render-app-backend:
    container_name: render-app-backend
    build: .
    ports:
      - 9090
    environment:
      ALLOWED_HOSTS: '*'
      CORS_ALLOWED_ORIGINS: 'http://unknown'
      CORS_ALLOWED_HEADERS: 'http://unknown'
      CORS_ORIGIN_WHITELIST: 'http://0.0.0.0;http://nginx;http://render-app-frontend;http://render-app-backend'
      MONGO_DB_ADDRESS: 'mongodb://mongo-router:27017'
      MONGO_SHARD_DB_NAME: 'render-app'
      MONGO_SHARD_COLLECTION_NAME: 'meta-data'
    volumes:
      - ./application/static/:/app/static
      - ./application/db.sqlite3:/app/db.sqlite3
    networks:
      - general
      - router-server_mongo-router
  
  nginx:
    container_name: nginx
    image: 'nginx:1.19.0-alpine'
    ports:
      - 80:80
      - 9090:9090
    volumes:
      - ./micro-services/nginx:/etc/nginx/conf.d
      - ./application/static:/static
      - ./../render-app-frontend/public:/usr/share/nginx/html/
    networks:
      - general

  redis:
    container_name: redis
    image: 'redis:5'
    networks:
      - general

networks:
  general:
    driver: bridge
  router-server_mongo-router:
    external: true