pip install django
pip install djangorestframework
pip install channels_redis
pip install drf_yasg
pip install pyjwt
pip install gevent
pip install gevent-tasks
pip install redis
pip install channels_redis
pip install djangochannelsrestframework
