pip install django
pip install djangorestframework
pip install channels_redis
pip install drf_yasg
pip install pyjwt
pip install asyncio
pip install websockets
pip install redis
pip install channels_redis
pip install djangochannelsrestframework
