version: '3.9'

services:
  # mongo config servers
  # master
  mongo-config-server-00:
    image: 'mongo:4.4.5'
    container_name: mongo-config-server-00
    environment: 
      PUID: 1000
      PGID: 1000
      TERM: xterm
    command: mongod --configsvr --replSet cfgrs --port 27017 --dbpath /data/db --bind_ip 0.0.0.0
    ports:
      - 50000:27017
    expose: 
      - "27017"
    volumes:
      - ./mongodb/config-servers/config-server-00/database:/data/db
    networks: 
      - mongo-config-and-shards

  # slaves
  mongo-config-server-01:
    image: 'mongo:4.4.5'
    container_name: mongo-config-server-01
    environment: 
      PUID: 1000
      PGID: 1000
      TERM: xterm
    command: mongod --configsvr --replSet cfgrs --port 27017 --dbpath /data/db --bind_ip 0.0.0.0
    ports:
      - 50001:27017
    expose: 
      - "27017"
    volumes:
      - ./mongodb/config-servers/config-server-01/database:/data/db
    networks: 
      - mongo-config-and-shards
  
  mongo-config-server-02:
    image: 'mongo:4.4.5'
    container_name: mongo-config-server-02
    environment: 
      PUID: 1000
      PGID: 1000
      TERM: xterm
    command: mongod --configsvr --replSet cfgrs --port 27017 --dbpath /data/db --bind_ip 0.0.0.0
    ports:
      - 50002:27017
    expose: 
      - "27017"
    volumes:
      - ./mongodb/config-servers/config-server-02/database:/data/db
    networks: 
      - mongo-config-and-shards
  
networks:
  mongo-config-and-shards:
    driver: bridge
