version: '3.9'

services:
  # mongo shard servers
  # master
  mongo-shard-00-server-00:
    image: 'mongo:4.4.4'
    container_name: mongo-shard-00-server-00
    command: mongod --shardsvr --replSet shard1rs --port 27017 --dbpath /data/db
    ports:
      - 60000:27017
    volumes: 
      - ./mongodb/shard-servers/shard-00-server-00/database:/data
    
  # slaves
  mongo-shard-00-server-01:
    image: 'mongo:4.4.4'
    container_name: mongo-shard-00-server-01
    command: mongod --shardsvr --replSet shard1rs --port 27017 --dbpath /data/db
    ports:
      - 60001:27017
    volumes: 
      - ./mongodb/shard-servers/shard-00-server-01/database:/data
  mongo-shard-00-server-02:
    image: 'mongo:4.4.4'
    container_name: mongo-shard-00-server-02
    command: mongod --shardsvr --replSet shard1rs --port 27017 --dbpath /data/db
    ports:
      - 60002:27017
    volumes: 
      - ./mongodb/shard-servers/shard-00-server-02/database:/data