version: '3.9'

services:
  # mongo shard servers
  # master
  mongo-shard-00-server-00:
    image: 'mongo:4.4.5'
    container_name: mongo-shard-00-server-00
    environment: 
      PUID: 1000
      PGID: 1000
      TERM: xterm
    command: mongod --shardsvr --replSet shard-00-rs --port 27017 --dbpath /data/db --bind_ip 0.0.0.0
    ports:
      - 60000:27017
    expose: 
      - "27017"
    volumes: 
      - ./mongodb/shard-servers/shard-00/server-00/database:/data/db
    networks: 
      - config-servers_mongo-config-and-shards
    
  # slaves
  mongo-shard-00-server-01:
    image: 'mongo:4.4.5'
    container_name: mongo-shard-00-server-01
    environment: 
      PUID: 1000
      PGID: 1000
      TERM: xterm
    command: mongod --shardsvr --replSet shard-00-rs --port 27017 --dbpath /data/db --bind_ip 0.0.0.0
    ports:
      - 60001:27017
    expose: 
      - "27017"
    volumes: 
      - ./mongodb/shard-servers/shard-00/server-01/database:/data/db
    networks: 
      - config-servers_mongo-config-and-shards
        
  mongo-shard-00-server-02:
    image: 'mongo:4.4.5'
    container_name: mongo-shard-00-server-02
    environment: 
      PUID: 1000
      PGID: 1000
      TERM: xterm
    command: mongod --shardsvr --replSet shard-00-rs --port 27017 --dbpath /data/db --bind_ip 0.0.0.0
    ports:
      - 60002:27017
    expose: 
      - "27017"
    volumes: 
      - ./mongodb/shard-servers/shard-00/server-02/database:/data/db
    networks: 
      - config-servers_mongo-config-and-shards

networks: 
  config-servers_mongo-config-and-shards:
    external: true