version: '3.9'

services:

  nginx:
    container_name: nginx
    image: 'nginx:1.19.0-alpine'
    ports:
      - 80:80
      - 9090:9090
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ../static:/static
      - ../../render-app-frontend/public:/usr/share/nginx/html/
    networks:
      - nginx

networks:
  nginx:
    driver: bridge