# Generated by Django 3.1.2 on 2021-02-16 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=600)),
                ('path', models.CharField(max_length=600)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.account')),
            ],
        ),
        migrations.CreateModel(
            name='RenderSetByVector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('resolution_x', models.IntegerField()),
                ('resolution_y', models.IntegerField()),
                ('name_series', models.IntegerField()),
                ('camera_id', models.IntegerField()),
                ('angle', models.FloatField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='render.model')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RenderSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('resolution_x', models.IntegerField()),
                ('resolution_y', models.IntegerField()),
                ('set_id', models.IntegerField()),
                ('rotate', models.FloatField()),
                ('name_series', models.IntegerField()),
                ('camera_id', models.IntegerField()),
                ('angle', models.FloatField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='render.model')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RenderImageByVector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('resolution_x', models.IntegerField()),
                ('resolution_y', models.IntegerField()),
                ('rotate', models.FloatField()),
                ('name_series', models.IntegerField()),
                ('camera_id', models.IntegerField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='render.model')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RenderImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('resolution_x', models.IntegerField()),
                ('resolution_y', models.IntegerField()),
                ('set_id', models.IntegerField()),
                ('rotate', models.FloatField()),
                ('name_series', models.IntegerField()),
                ('camera_id', models.IntegerField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='render.model')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RenderAll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('resolution_x', models.IntegerField()),
                ('resolution_y', models.IntegerField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='render.model')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FingerVectorsDictSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IK_nadgarstek_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_joint3_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_joint4_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_joint5_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_joint6_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_maly_1_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_maly_2_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_maly_3_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_serdeczny_1_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_serdeczny_2_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_serdeczny_3_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_srodkowy_1_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_srodkowy_2_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_srodkowy_3_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_wskazujacy_1_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_wskazujacy_2_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_wskazujacy_3_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_kciuk_0_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_kciuk_1_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_kciuk_2_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('render', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='render.rendersetbyvector')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FingerVectorsDictImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IK_nadgarstek_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_joint3_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_joint4_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_joint5_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_joint6_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_maly_1_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_maly_2_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_maly_3_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_serdeczny_1_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_serdeczny_2_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_serdeczny_3_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_srodkowy_1_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_srodkowy_2_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_srodkowy_3_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_wskazujacy_1_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_wskazujacy_2_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_wskazujacy_3_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_kciuk_0_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_kciuk_1_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_kciuk_2_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('render', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='render.renderimagebyvector')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
