# Generated by Django 3.1.2 on 2021-02-16 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('model', models.FileField(upload_to='models/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
            ],
        ),
        migrations.CreateModel(
            name='RenderAll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('images_width', models.IntegerField()),
                ('images_height', models.IntegerField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='render.model')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RenderImage',
            fields=[
                ('renderall_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='render.renderall')),
                ('setID', models.IntegerField()),
                ('cameraID', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('render.renderall',),
        ),
        migrations.CreateModel(
            name='RenderImageByVector',
            fields=[
                ('renderimage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='render.renderimage')),
            ],
            options={
                'abstract': False,
            },
            bases=('render.renderimage',),
        ),
        migrations.CreateModel(
            name='RenderSet',
            fields=[
                ('renderimage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='render.renderimage')),
                ('angle', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
            bases=('render.renderimage',),
        ),
        migrations.CreateModel(
            name='RenderSetByVector',
            fields=[
                ('renderset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='render.renderset')),
            ],
            options={
                'abstract': False,
            },
            bases=('render.renderset',),
        ),
        migrations.CreateModel(
            name='FingerVectorsDictImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IK_nadgarstek_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_joint3_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_joint4_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_joint5_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_joint6_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_maly_1_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_maly_2_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_maly_3_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_serdeczny_1_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_serdeczny_2_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_serdeczny_3_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_srodkowy_1_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_srodkowy_2_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_srodkowy_3_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_wskazujacy_1_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_wskazujacy_2_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_wskazujacy_3_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_kciuk_0_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_kciuk_1_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_kciuk_2_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('render', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='render.renderimagebyvector')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FingerVectorsDictSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IK_nadgarstek_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_joint3_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_joint4_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_joint5_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_joint6_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_maly_1_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_maly_2_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_maly_3_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_serdeczny_1_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_serdeczny_2_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_serdeczny_3_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_srodkowy_1_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_srodkowy_2_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_srodkowy_3_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_wskazujacy_1_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_wskazujacy_2_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_wskazujacy_3_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_kciuk_0_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_kciuk_1_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('IK_kciuk_2_R', models.CharField(max_length=100, verbose_name='{"scale": 0.0, "y": 0.0, "x": 0.0, "z": 0.0}')),
                ('render', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='render.rendersetbyvector')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
