# Generated by Django 3.1.2 on 2020-10-16 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renderset',
            name='images_count',
        ),
    ]
