version: '3.9'

services:
  mongo-router:
    image: 'mongo:4.4.4'
    container_name: mongo-router
    environment: 
      PUID: 1000
      PGID: 1000
    volumes: 
      - ./mongodb/router-server/router/database:/data
    command: mongos --configdb cfgrs/192.168.1.10:50000,192.168.1.10:50000,192.168.1.10:50000 --bind_ip 0.0.0.0 --port 27017
    ports:
      - 40000:27017
